import { useEffect, useState } from 'react'
import { useAuth } from '../context/AuthContext.jsx'
import { Modal } from './Modal.jsx'

const blank = (fields) => Object.fromEntries(fields.map((field) => [field.name, field.default ?? '']))

function ResourceForm({ fields, item, onSave, onClose, submitting, error }) {
  const [values, setValues] = useState(item ? { ...blank(fields), ...item } : blank(fields))
  const [clientError, setClientError] = useState('')
  const submit = (event) => { event.preventDefault(); if (fields.some((field) => field.required && !values[field.name])) { setClientError('Complete all required fields.'); return } onSave(values) }
  return <form onSubmit={submit} className="space-y-4">{(clientError || error?.message) && <p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{clientError || error.message}</p>}{fields.map((field) => <label key={field.name} className="block text-sm font-medium text-slate-700">{field.label}{field.required && ' *'}{field.type === 'select' ? <select value={values[field.name] ?? ''} onChange={(e) => setValues({ ...values, [field.name]: e.target.value })} className="mt-1 w-full rounded border border-slate-300 px-3 py-2">{field.options.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input type={field.type || 'text'} required={field.required} value={values[field.name] ?? ''} onChange={(e) => setValues({ ...values, [field.name]: e.target.value })} className="mt-1 w-full rounded border border-slate-300 px-3 py-2" />}{error?.validationErrors?.[field.name] && <span className="mt-1 block text-xs text-red-700">{error.validationErrors[field.name][0]}</span>}</label>)}<div className="flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded px-4 py-2">Cancel</button><button disabled={submitting} className="rounded bg-blue-600 px-4 py-2 text-white disabled:opacity-60">{submitting ? 'Saving…' : 'Save'}</button></div></form>
}

export function ReferenceDataPage({ title, service, fields, columns }) {
  const { hasRole } = useAuth(); const canManage = hasRole('Admin', 'Staff')
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [notice, setNotice] = useState(''); const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null); const [submitting, setSubmitting] = useState(false)
  const load = async () => { setLoading(true); setError(null); try { const page = await service.list(); setRecords(page.data ?? []) } catch (apiError) { setError(apiError) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const save = async (values) => { setSubmitting(true); setError(null); try { if (editing?.id) await service.update(editing.id, values); else await service.create(values); setEditing(null); setNotice('Saved successfully.'); await load() } catch (apiError) { setError(apiError) } finally { setSubmitting(false) } }
  const remove = async () => { setSubmitting(true); setError(null); try { await service.remove(deleting.id); setDeleting(null); setNotice('Deleted successfully.'); await load() } catch (apiError) { setError(apiError) } finally { setSubmitting(false) } }
  return <section><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold text-slate-900">{title}</h2><p className="mt-1 text-slate-600">Manage reference data from the Laboratory 2 API.</p></div>{canManage && <button onClick={() => { setError(null); setEditing({}) }} className="rounded bg-blue-600 px-4 py-2 text-white">Add {title.slice(0, -1)}</button>}</div>{notice && <p className="mb-4 rounded bg-green-50 p-3 text-sm text-green-700">{notice}</p>}{error && !editing && <p role="alert" className="mb-4 rounded bg-red-50 p-3 text-sm text-red-700">{error.status === 403 ? 'Access denied.' : error.message}</p>}{loading ? <p className="text-slate-600">Loading…</p> : records.length === 0 ? <p className="rounded border border-dashed p-6 text-slate-600">No {title.toLowerCase()} found.</p> : <div className="overflow-x-auto rounded border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{columns.map((column) => <th key={column.name} className="px-4 py-3">{column.label}</th>)}{canManage && <th className="px-4 py-3">Actions</th>}</tr></thead><tbody>{records.map((record) => <tr key={record.id} className="border-t">{columns.map((column) => <td key={column.name} className="px-4 py-3">{record[column.name] ?? '—'}</td>)}{canManage && <td className="px-4 py-3"><button onClick={() => { setError(null); setEditing(record) }} className="mr-3 text-blue-700">Edit</button><button onClick={() => setDeleting(record)} className="text-red-700">Delete</button></td>}</tr>)}</tbody></table></div>}{editing && <Modal title={`${editing.id ? 'Edit' : 'Add'} ${title.slice(0, -1)}`} onClose={() => setEditing(null)}><ResourceForm fields={fields} item={editing.id ? editing : null} onSave={save} onClose={() => setEditing(null)} submitting={submitting} error={error} /></Modal>}{deleting && <Modal title={`Delete ${title.slice(0, -1)}`} onClose={() => setDeleting(null)}><p className="text-slate-600">Delete this record? This cannot be undone.</p>{error && <p className="mt-3 text-sm text-red-700">{error.message}</p>}<div className="mt-5 flex justify-end gap-3"><button onClick={() => setDeleting(null)}>Cancel</button><button disabled={submitting} onClick={remove} className="rounded bg-red-600 px-4 py-2 text-white disabled:opacity-60">Delete</button></div></Modal>}</section>
}
